spring.application.name=Ai-Study-Assistant-Backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/study_assistant_db
spring.datasource.username=ai_user
spring.datasource.password=secure_password
spring.jpa.hibernate.ddl-auto=update

# FastAPI Microservice Routing
ai.microservice.base-url=http://127.0.0.1:8000

# ===============================
# MinIO Configuration
# ===============================
minio.url=http://127.0.0.1:9000
minio.access.name=admin
minio.access.secret=password123
minio.bucket.name=study-materials

# ===============================
# Valkey (Redis) Configuration
# ===============================
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

#Setting the file size limit to 50 MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB